//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbragimovIlshatCarDealership
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Media;

    public partial class Car
    {
        public Car()
        {
            this.Sale = new HashSet<Sale>();
        }

        public int CarID { get; set; }
        public int MarkID { get; set; }
        public string MarkString
        {
            get
            {
                return Mark.MarkName;
            }
        }


        public string Model { get; set; }
        public int YearProduct { get; set; }
        public string Color { get; set; }
        public int ClassID { get; set; }
        public string ClassString
        {
            get
            {
                return Class.ClassName;
            }
        }

        public string Description { get; set; }
        public int Price { get; set; }
        public Nullable<int> Count { get; set; }
        public string Image { get; set; }

        public SolidColorBrush FontStyle
        {
            get
            {
                if (Count == 0)
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("#ab1515");
                else
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("#FFFFFF");
            }
        }
        public virtual ICollection<Sale> Sale { get; set; }
        public virtual Class Class { get; set; }
        public virtual Mark Mark { get; set; }
    }
}
