//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbragimovIlshatCarDealership
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory
    {
        public Factory()
        {
            this.Mark = new HashSet<Mark>();
        }
    
        public int FactoryID { get; set; }
        public string FactoryName { get; set; }
        public string Country { get; set; }
        public string Addres { get; set; }
    
        public virtual ICollection<Mark> Mark { get; set; }
    }
}
