//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbragimovIlshatCarDealership
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IbragimovCarDealershipDBEntities : DbContext
    {
        public static IbragimovCarDealershipDBEntities _content;

        public static IbragimovCarDealershipDBEntities GetContext()
        {
            if (_content == null)
            {
                _content = new IbragimovCarDealershipDBEntities();
            }

            return _content;
        }
        public IbragimovCarDealershipDBEntities()
            : base("name=IbragimovCarDealershipDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Car> Car { get; set; }
        public DbSet<Class> Class { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Factory> Factory { get; set; }
        public DbSet<Mark> Mark { get; set; }
        public DbSet<Post> Post { get; set; }
        public DbSet<Sale> Sale { get; set; }
        public DbSet<Worker> Worker { get; set; }
    }
}
