//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbragimovIlshatCarDealership
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public Mark()
        {
            this.Car = new HashSet<Car>();
        }
    
        public int MarkID { get; set; }
        public string MarkName { get; set; }
        public int FactoryID { get; set; }
    
        public virtual ICollection<Car> Car { get; set; }
        public virtual Factory Factory { get; set; }
    }
}
