//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbragimovIlshatCarDealership
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Worker = new HashSet<Worker>();
        }
    
        public int PostID { get; set; }
        public string PostName { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        public virtual ICollection<Worker> Worker { get; set; }
    }
}
