//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbragimovIlshatCarDealership
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.Sale = new HashSet<Sale>();
        }
    
        public int WorkerID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public int WorkRecord { get; set; }
        public int PostID { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
